# Generated by Django 3.2.4 on 2021-06-25 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Leaderboard', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
    ]
